INSERT INTO CURRENCY VALUES (1,  1, '2018-12-16 12:11:00', 'PLN');
INSERT INTO CURRENCY VALUES (2,  4.76, '2018-12-16 12:11:00', 'GPB');

INSERT INTO DRIVER_TYPE VALUES(1, 1, 'regular', 1.5, 2);
INSERT INTO DRIVER_TYPE VALUES(2, 0, 'disabled', 1.25, 2);
INSERT INTO DRIVER_TYPE VALUES(3, 0, 'owner', 0, 0);

INSERT INTO ROLE VALUES (1, 'OWNER');
INSERT INTO ROLE VALUES (2, 'DRIVER');
INSERT INTO ROLE VALUES (3, 'OPERATOR');
INSERT INTO ROLE VALUES (4, 'ADMIN');

INSERT INTO USER(ID, EMAIL, ENABLED, FIRST_NAME, LAST_NAME, USER_NAME, NON_LOCKED, PASSWORD, PHONE_NUMBER, CURRENCY_ID, DRIVER_TYPE_ID, CREATED_DATE) VALUES(1, 'owner@wp.pl', TRUE, 'Jakub', 'Wierzbicki', 'Owner', TRUE, 'passwd', 737737737, 2, 1, '2018-12-16 12:11:00');
INSERT INTO USER(ID, EMAIL, ENABLED, FIRST_NAME, LAST_NAME, USER_NAME, NON_LOCKED, PASSWORD, PHONE_NUMBER, CURRENCY_ID, DRIVER_TYPE_ID, CREATED_DATE) VALUES(2, 'driver@wp.pl', TRUE, 'Jakub', 'Wierzbicki', 'Driver', TRUE, 'passwd', 737737737,2, 1, '2018-12-16 12:11:00');
INSERT INTO USER(ID, EMAIL, ENABLED, FIRST_NAME, LAST_NAME, USER_NAME, NON_LOCKED, PASSWORD, PHONE_NUMBER, CURRENCY_ID, DRIVER_TYPE_ID, CREATED_DATE) VALUES(3, 'operator@wp.pl', TRUE, 'Jakub', 'Wierzbicki', 'Operator', TRUE, 'passwd', 737737737,2, 1, '2018-12-16 12:11:00');

INSERT INTO USER_ROLES VALUES(1, 1);
INSERT INTO USER_ROLES VALUES(1, 2);
INSERT INTO USER_ROLES VALUES(1, 3);
INSERT INTO USER_ROLES VALUES(1, 4);

INSERT INTO USER_ROLES VALUES(2, 2);
INSERT INTO USER_ROLES VALUES(3, 3);